---
title: "tmp"
output: 
  html_document:
    toc: true
    theme: flatly
---

```{r include=FALSE}
library(tidyverse)
library(ggpubr)
library(corrplot)
library(pheatmap)
library(knitr)
library(rmarkdown)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

# Section 1 {.tabset}

```{r}
df <- tibble(method = c(LETTERS[1:10]),
             performance = runif(10))
df2 <- tibble(method = c(LETTERS[11:20]),
             performance = runif(10))
df3 <- tibble(method = c(LETTERS[21:26]),
             performance = runif(6))
matrix <- matrix(runif(100), nrow = 10, ncol = 10)
colnames(matrix) <- LETTERS[1:10]
rownames(matrix) <- LETTERS[1:10]

#https://bookdown.org/yihui/rmarkdown-cookbook/font-color.html
#custom function to change color of Rmd text 
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}
```

## First part of alphabet

```{r}
kable(df)
```

## Second part of alphabet

```{r}
kable(df2)
```

## Last part of alphabet

```{r}
kable(df3)
```

# Section 2
## header 2 
### header 3
#### header 4 
##### header 5
Normal body of text

```{r}
pheatmap(matrix)
```

# Section 3
```{r}
df %>% 
  ggplot(aes(x = method, y = performance)) +
  geom_col() +
  theme_minimal()
```
